name: reviewdog
on: [pull_request]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dbelyaev/action-checkstyle@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          fail_level: error
          checkstyle_config: google_checks.xml